// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file DataSample.hpp
 * This header file contains the declaration of the described types in the IDL file.
 *
 * This file was generated by the tool fastddsgen (version: 4.3.0).
 */

#ifndef FAST_DDS_GENERATED__DATASAMPLE_IDL_HPP
#define FAST_DDS_GENERATED__DATASAMPLE_IDL_HPP

#include <cstdint>
#include <string>
#include <utility>
#include <fastcdr/cdr/fixed_size_string.hpp>

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#define eProsima_user_DllExport __declspec( dllexport )
#else
#define eProsima_user_DllExport
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define eProsima_user_DllExport
#endif  // _WIN32

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#if defined(DATASAMPLE_SOURCE)
#define DATASAMPLE_DllAPI __declspec( dllexport )
#else
#define DATASAMPLE_DllAPI __declspec( dllimport )
#endif // DATASAMPLE_SOURCE
#else
#define DATASAMPLE_DllAPI
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define DATASAMPLE_DllAPI
#endif // _WIN32

/*!
 * @brief This class represents the structure DataSample defined by the user in the IDL file.
 * @ingroup DataSample
 */
class DataSample
{
public:

    /*!
     * @brief Default constructor.
     */
    eProsima_user_DllExport DataSample()
    {
    }

    /*!
     * @brief Default destructor.
     */
    eProsima_user_DllExport ~DataSample()
    {
    }

    /*!
     * @brief Copy constructor.
     * @param x Reference to the object DataSample that will be copied.
     */
    eProsima_user_DllExport DataSample(
            const DataSample& x)
    {
                    m_id = x.m_id;

                    m_timestamp = x.m_timestamp;

                    m_message = x.m_message;

    }

    /*!
     * @brief Move constructor.
     * @param x Reference to the object DataSample that will be copied.
     */
    eProsima_user_DllExport DataSample(
            DataSample&& x) noexcept
    {
        m_id = x.m_id;
        m_timestamp = x.m_timestamp;
        m_message = std::move(x.m_message);
    }

    /*!
     * @brief Copy assignment.
     * @param x Reference to the object DataSample that will be copied.
     */
    eProsima_user_DllExport DataSample& operator =(
            const DataSample& x)
    {

                    m_id = x.m_id;

                    m_timestamp = x.m_timestamp;

                    m_message = x.m_message;

        return *this;
    }

    /*!
     * @brief Move assignment.
     * @param x Reference to the object DataSample that will be copied.
     */
    eProsima_user_DllExport DataSample& operator =(
            DataSample&& x) noexcept
    {

        m_id = x.m_id;
        m_timestamp = x.m_timestamp;
        m_message = std::move(x.m_message);
        return *this;
    }

    /*!
     * @brief Comparison operator.
     * @param x DataSample object to compare.
     */
    eProsima_user_DllExport bool operator ==(
            const DataSample& x) const
    {
        return (m_id == x.m_id &&
           m_timestamp == x.m_timestamp &&
           m_message == x.m_message);
    }

    /*!
     * @brief Comparison operator.
     * @param x DataSample object to compare.
     */
    eProsima_user_DllExport bool operator !=(
            const DataSample& x) const
    {
        return !(*this == x);
    }

    /*!
     * @brief This function sets a value in member id
     * @param _id New value for member id
     */
    eProsima_user_DllExport void id(
            uint32_t _id)
    {
        m_id = _id;
    }

    /*!
     * @brief This function returns the value of member id
     * @return Value of member id
     */
    eProsima_user_DllExport uint32_t id() const
    {
        return m_id;
    }

    /*!
     * @brief This function returns a reference to member id
     * @return Reference to member id
     */
    eProsima_user_DllExport uint32_t& id()
    {
        return m_id;
    }


    /*!
     * @brief This function sets a value in member timestamp
     * @param _timestamp New value for member timestamp
     */
    eProsima_user_DllExport void timestamp(
            uint64_t _timestamp)
    {
        m_timestamp = _timestamp;
    }

    /*!
     * @brief This function returns the value of member timestamp
     * @return Value of member timestamp
     */
    eProsima_user_DllExport uint64_t timestamp() const
    {
        return m_timestamp;
    }

    /*!
     * @brief This function returns a reference to member timestamp
     * @return Reference to member timestamp
     */
    eProsima_user_DllExport uint64_t& timestamp()
    {
        return m_timestamp;
    }


    /*!
     * @brief This function copies the value in member message
     * @param _message New value to be copied in member message
     */
    eProsima_user_DllExport void message(
            const std::string& _message)
    {
        m_message = _message;
    }

    /*!
     * @brief This function moves the value in member message
     * @param _message New value to be moved in member message
     */
    eProsima_user_DllExport void message(
            std::string&& _message)
    {
        m_message = std::move(_message);
    }

    /*!
     * @brief This function returns a constant reference to member message
     * @return Constant reference to member message
     */
    eProsima_user_DllExport const std::string& message() const
    {
        return m_message;
    }

    /*!
     * @brief This function returns a reference to member message
     * @return Reference to member message
     */
    eProsima_user_DllExport std::string& message()
    {
        return m_message;
    }



private:

    uint32_t m_id{0};
    uint64_t m_timestamp{0};
    std::string m_message;

};

#endif // _FAST_DDS_GENERATED_DATASAMPLE_IDL_HPP_


